function template = create_atlas( I, label )
% create an atlas by asking a user to manually label a template image.
%
% inputs
%   I: image matrix
%   label: a label string for the atlas (e.g. 'CA')
%
% outputs
%   template: an object that contains all the atlas data.
%   template.label: the label string
%   template.original_image: the original input image
%   template.foreground_image: original_image - background - labelled ROIs
%   template.rois: a list of ROI cell, each cell contains the name
%   of the ROI and its coordinate.

message_template = ...
    'Please click on the top left and right bottom points of the %s';

roi_names = {...
    'foreground',...
    'photo',...
    'signature',...
    'DL',...
    'EXP',...
    'LN',...
    'FN',...
    'address',...
    'DOB',...
    'RSTR',...
    'CLASS',...
    'END',...
    'SEX',...
    'HAIR',...
    'EYES',...
    'HGT',...
    'WGT',...
    'DD',...
    'ISS'...
};

template.label = label;
template.original_image = I;

figure; imagesc(I);

num_rois = 2; %size(roi_names, 2);
for i = 1:num_rois
    msgbox(sprintf(message_template, roi_names{i}));
    coord = ginput(2);
    template.rois{i} = struct('name', roi_names{i}, 'coord', coord);
end

foreground_image = I;

% clear all the ROI image except the foreground
for i = 2:num_rois
    coord = template.rois{i}.coord;
    foreground_image(coord(1,2):coord(2,2),coord(1,1):coord(2,1),:) = 0;
end

% clear all pixels outside foreground
foreground_mask = zeros(size(I));
coord = template.rois{1}.coord;
foreground_mask(coord(1,2):coord(2,2),coord(1,1):coord(2,1),:) = 1;
foreground_image = foreground_image .* uint8(foreground_mask);

template.foreground_image = foreground_image;
end
